<a href="https://colab.research.google.com/github/RafaelSpumbergSeus/An-lise-Pr--processamento-e-Visualiza-o-de-Dados/blob/main/DadosSujos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!git clone https://github.com/RafaelSpumbergSeus/An-lise-Pr--processamento-e-Visualiza-o-de-Dados.git

Cloning into 'An-lise-Pr--processamento-e-Visualiza-o-de-Dados'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), 9.78 KiB | 9.78 MiB/s, done.


In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
import os

repo_path = '/content/An-lise-Pr--processamento-e-Visualiza-o-de-Dados'

print("Conteúdo do repositório:")
print(os.listdir(repo_path))

Conteúdo do repositório:
['.git', 'DadosICDSujos.xlsx']


In [13]:
caminho_arquivo = '/content/An-lise-Pr--processamento-e-Visualiza-o-de-Dados/data/DadosICDSujos.xlsx'

In [14]:
import pandas as pd
caminho_arquivo = '/content/An-lise-Pr--processamento-e-Visualiza-o-de-Dados/DadosICDSujos.xlsx'
df = pd.read_excel(caminho_arquivo)
df.head()

ID Gênero  Idade Tipo_Escola Renda_Familiar  Horas_Estudo Presença_Aulas  \
0   1      F     16     Pública          Baixa             5            90%   
1   2      M     17  Particular          Média             3            85%   
2   3      F     15     Pública           Alta             8            95%   
3   4      M     16  Particular          Média             2            70%   
4   5      F     17     Pública          Baixa             6            80%   

   Nota_Avaliacao_1  Nota_Avaliacao_2 Atividade_Extra Tempo_Lazer  \
0               7.5               8.0             Sim     8 horas   
1               6.0               6.5             Não     7 horas   
2               9.0               9.5             Sim     5 horas   
3               5.0               5.5             Não     6 horas   
4               7.0               7.5             Sim     8 horas   

  Transporte_Escola  
0            Ônibus  
1             Carro  
2         Bicicleta  
3             Carro  
4            Ônibus

In [17]:
df.isnull().sum()
df.fillna(0, inplace=True)

In [20]:
print(df['Idade'].unique())

[ 16  17  15  14 -15 160]


In [29]:
df['Idade'] = df['Idade'].replace(-15, 15)
df['Idade'] = df['Idade'].replace(160, 16)

In [30]:
print(df['Idade'].unique())

[16 17 15 14]


In [23]:
print(df['Tipo_Escola'].unique())

['Pública' 'Particular' 'particuuular' 'pub' 'pblica']


In [24]:
df = df.replace('particuuular', 'Particular')
df = df.replace('pub', 'Pública')
df = df.replace('pblica', 'Pública')

In [25]:
print(df['Tipo_Escola'].unique())

['Pública' 'Particular']


In [31]:
print(df['Horas_Estudo'].unique())

[   5    3    8    2    6    4    7 4000]


In [32]:
df['Horas_Estudo'] = df['Horas_Estudo'].replace(4000, 4)
print(df['Horas_Estudo'].unique())

[5 3 8 2 6 4 7]
